<?php
/**
 * Blue Rocket Co. — Contact Form Handler
 * PHP mailer for shared hosting (cPanel / Namecheap etc.)
 *
 * Security layers applied:
 *  1. HTTPS-only enforcement
 *  2. CORS — only accepts requests from the site's own origin
 *  3. CSRF token validation (stateless HMAC, no session needed)
 *  4. Rate limiting  — max 5 submissions per IP per 15 minutes (file-lock)
 *  5. Honeypot field — bots fill it, humans don't
 *  6. Input sanitisation and strict length limits
 *  7. Output escaping before any value reaches the email body
 *  8. No user-supplied data ever reaches PHP mail() headers
 */

declare(strict_types=1);

/* ─── Site configuration ──────────────────────────────────────────── */
define('ALLOWED_ORIGIN',   'https://bluerocketcompany.com');
define('TO_EMAIL',         'bluerocketco.7@gmail.com');
define('FROM_EMAIL',       'noreply@bluerocketcompany.com');
define('FROM_NAME',        'Blue Rocket Co. Website');
define('CSRF_SECRET',      '9b418d42ec6e72911f4d2d7eb4262916af162324d6d9e8a1bf52d36fd5494879');
define('RATE_LIMIT_DIR',   dirname(__DIR__) . '/br_ratelimit/');
define('RATE_LIMIT_MAX',   5);    // requests
define('RATE_LIMIT_WINDOW', 900); // seconds (15 min)

/* ─── Helpers ─────────────────────────────────────────────────────── */
function json_out(int $code, array $data): void {
    http_response_code($code);
    header('Content-Type: application/json; charset=utf-8');
    echo json_encode($data, JSON_UNESCAPED_UNICODE);
    exit;
}

function clean(string $value, int $maxLen = 500): string {
    $v = trim($value);
    $v = mb_substr($v, 0, $maxLen);
    return htmlspecialchars($v, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

function get_ip(): string {
    foreach (['HTTP_CF_CONNECTING_IP', 'HTTP_X_FORWARDED_FOR', 'REMOTE_ADDR'] as $key) {
        $ip = $_SERVER[$key] ?? '';
        if ($ip !== '') {
            return explode(',', $ip)[0];
        }
    }
    return '0.0.0.0';
}

/* ─── HTTPS enforcement ───────────────────────────────────────────── */
if (
    (!isset($_SERVER['HTTPS']) || $_SERVER['HTTPS'] !== 'on') &&
    ($_SERVER['HTTP_X_FORWARDED_PROTO'] ?? '') !== 'https'
) {
    // On shared hosting behind a CDN this header check is safer than
    // a redirect, which can loop. Just refuse the request.
    json_out(403, ['error' => 'HTTPS required.']);
}

/* ─── CORS ────────────────────────────────────────────────────────── */
$origin = $_SERVER['HTTP_ORIGIN'] ?? '';

/* Some shared hosting proxies strip Origin — fall back to Referer */
if ($origin === '' && !empty($_SERVER['HTTP_REFERER'])) {
    $parts = parse_url($_SERVER['HTTP_REFERER']);
    if ($parts !== false && isset($parts['scheme'], $parts['host'])) {
        $origin = $parts['scheme'] . '://' . $parts['host'];
        if (isset($parts['port'])) $origin .= ':' . $parts['port'];
    }
}

header('Vary: Origin');

if ($origin === ALLOWED_ORIGIN) {
    header('Access-Control-Allow-Origin: ' . ALLOWED_ORIGIN);
    header('Access-Control-Allow-Methods: POST, OPTIONS');
    header('Access-Control-Allow-Headers: Content-Type, X-CSRF-Token');
    header('Access-Control-Max-Age: 86400');
} else {
    json_out(403, ['error' => 'Origin not allowed.']);
}

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    http_response_code(204);
    exit;
}

/* ─── Method guard ────────────────────────────────────────────────── */
if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    json_out(405, ['error' => 'Method not allowed.']);
}

/* ─── Parse body ──────────────────────────────────────────────────── */
$raw  = file_get_contents('php://input');
$body = json_decode($raw, true);

if (!is_array($body)) {
    json_out(400, ['error' => 'Invalid request body.']);
}

/* ─── CSRF (stateless HMAC token) ────────────────────────────────── */
//
// The token is generated by the JS frontend as:
//   HMAC-SHA256( secret, "contact:" + date("Y-m-d") )
// Valid for today + yesterday (handles midnight edge).
//
$token = trim($_SERVER['HTTP_X_CSRF_TOKEN'] ?? ($body['_csrf'] ?? ''));

function make_csrf_token(string $date): string {
    return hash_hmac('sha256', 'contact:' . $date, CSRF_SECRET);
}

$today     = date('Y-m-d');
$yesterday = date('Y-m-d', strtotime('-1 day'));
$validTokens = [make_csrf_token($today), make_csrf_token($yesterday)];

if (!in_array($token, $validTokens, true)) {
    json_out(403, ['error' => 'Invalid or missing security token.']);
}

/* ─── Rate limiting ───────────────────────────────────────────────── */
$ip       = get_ip();
$ipHash   = hash('sha256', $ip); // never store raw IPs
$rateFile = RATE_LIMIT_DIR . $ipHash;

if (!is_dir(RATE_LIMIT_DIR)) {
    mkdir(RATE_LIMIT_DIR, 0700, true);
}

$fp = @fopen($rateFile, 'c+');
if ($fp) {
    flock($fp, LOCK_EX);
    $data = json_decode(fread($fp, 256) ?: '{}', true);

    $now = time();
    if (!isset($data['count']) || ($now - ($data['ts'] ?? 0)) > RATE_LIMIT_WINDOW) {
        $data = ['count' => 0, 'ts' => $now];
    }

    $data['count']++;
    if ($data['count'] > RATE_LIMIT_MAX) {
        flock($fp, LOCK_UN);
        fclose($fp);
        json_out(429, ['error' => 'Too many submissions. Please wait 15 minutes and try again.']);
    }

    rewind($fp);
    ftruncate($fp, 0);
    fwrite($fp, json_encode($data));
    flock($fp, LOCK_UN);
    fclose($fp);
}

/* ─── Honeypot ────────────────────────────────────────────────────── */
if (!empty($body['_hp'])) {
    // Silently succeed — let bots think it worked
    json_out(200, ['success' => true]);
}

/* ─── Validate and sanitise fields ───────────────────────────────── */
$errors = [];

$name      = clean($body['name']      ?? '', 120);
$email     = clean($body['email']     ?? '', 254);
$company   = clean($body['company']   ?? '', 200);
$phone     = clean($body['phone']     ?? '', 30);
$challenge = clean($body['challenge'] ?? '', 3000);

if (mb_strlen($name) < 2)       $errors['name']      = 'Name is required (min 2 characters).';
if (!filter_var(
        html_entity_decode($email, ENT_QUOTES, 'UTF-8'),
        FILTER_VALIDATE_EMAIL
   ))                             $errors['email']     = 'A valid email address is required.';
if (mb_strlen($company) < 2)    $errors['company']   = 'Company is required.';
if (mb_strlen($challenge) < 10) $errors['challenge'] = 'Please describe your challenge (min 10 characters).';

if (!empty($errors)) {
    json_out(422, ['errors' => $errors]);
}

/* ─── Build the email ─────────────────────────────────────────────── */
// All values are already HTML-escaped by clean(). We decode for plain-text email.
function plain(string $v): string {
    return html_entity_decode($v, ENT_QUOTES, 'UTF-8');
}

$namePlain      = plain($name);
$emailPlain     = plain($email);
$companyPlain   = plain($company);
$phonePlain     = plain($phone);
$challengePlain = plain($challenge);

$subject = 'New inquiry — Blue Rocket Co. website';

$textBody = <<<TEXT
New inquiry from the Blue Rocket Co. website
============================================

Name:     {$namePlain}
Email:    {$emailPlain}
Company:  {$companyPlain}
Phone:    {$phonePlain}

Challenge:
{$challengePlain}

---
Sent: {$today}
IP hash: {$ipHash}
TEXT;

// Build safe headers — NO user data allowed here
$headers  = "From: " . FROM_NAME . " <" . FROM_EMAIL . ">\r\n";
$headers .= "Reply-To: " . FROM_NAME . " <" . FROM_EMAIL . ">\r\n";
$headers .= "X-Mailer: PHP/" . PHP_VERSION . "\r\n";
$headers .= "MIME-Version: 1.0\r\n";
$headers .= "Content-Type: text/plain; charset=UTF-8\r\n";
$headers .= "Content-Transfer-Encoding: 8bit\r\n";

$sent = mail(TO_EMAIL, $subject, $textBody, $headers, '-f' . FROM_EMAIL);

if (!$sent) {
    json_out(500, ['error' => 'Failed to send email. Please contact us directly at ' . TO_EMAIL]);
}

json_out(200, ['success' => true]);
